upstream web_backend {    
    server 192.168.135.111;
    server 192.168.135.112; 
}

server {
        listen 80; 

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://web_backend;
        }
}

